name = "live-screen-share-code-service"
main = "src/index.js"
compatibility_date = "2026-02-17"

[[kv_namespaces]]
binding = "JOIN_CODES"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_PREVIEW_NAMESPACE_ID"

[vars]
DEFAULT_TTL_SECONDS = "900"
